import {test} from 'node:test';
import assert from 'node:assert/strict';
import {elapsed,matches,type Timer} from '../lib/timers.ts';
import {assertEventDate,assertTimerDate,timerInput} from '../lib/validation.ts';
const t:Timer={id:'t',workspaceId:'w',folderId:null,title:'Fast food',note:'Takeaway',kind:'since',startedAt:'2026-10-01T00:00:00.000Z',counter:true,labels:['food','health'],color:'peach',emoji:'🍔',count:0,lastEvent:null};
test('a reset uses event time rather than initial start',()=>{assert.deepEqual(elapsed({...t,lastEvent:'2026-10-05T01:02:03.000Z',count:1},Date.parse('2026-10-06T03:04:06.000Z')),{days:1,hours:2,minutes:2,seconds:3,done:false})});
test('countdown reaches zero and never becomes negative',()=>{assert.equal(elapsed({...t,kind:'until'},Date.parse('2026-10-02T00:00:00Z')).days,0);assert.equal(elapsed({...t,kind:'until'},Date.parse('2026-10-02T00:00:00Z')).done,true)});
test('search matches titles, notes and #labels without case sensitivity',()=>{assert.equal(matches(t,'#HEALTH',''),true);assert.equal(matches(t,'TAKEAWAY','food'),true);assert.equal(matches(t,'','travel'),false)});
test('counter remains derived from recorded events, not elapsed days',()=>{assert.equal(elapsed(t,Date.parse('2026-10-06T00:00:00Z')).days,5);assert.equal(t.count,0)});
test('reject future events and events before initial start',()=>{assert.throws(()=>assertEventDate('2026-10-07T00:00:00Z',t.startedAt,Date.parse('2026-10-06T00:00:00Z')));assert.throws(()=>assertEventDate('2026-09-01T00:00:00Z',t.startedAt));assert.throws(()=>assertTimerDate('since','2026-10-07T00:00:00Z',Date.parse('2026-10-06T00:00:00Z')))});
test('labels are normalized and duplicate labels removed',()=>{const parsed=timerInput.parse({...t,labels:[' Health ','health','Food']});assert.deepEqual(parsed.labels,['health','food']);assert.throws(()=>timerInput.parse({...t,title:'   '}));assert.throws(()=>timerInput.parse({...t,labels:['<script>']}))});
