import { getChatGPTUser } from '@/app/chatgpt-auth';
import { database } from '@/lib/storage';
import { timerInput,eventInput,namedInput,labelName,assertEventDate,assertTimerDate } from '@/lib/validation';
import type { Timer } from '@/lib/timers';
class Problem extends Error{constructor(message:string,public status=400){super(message)}}
const cacheHeaders={'Cache-Control':'no-store'};
async function owner(){const user=await getChatGPTUser();if(!user)throw new Problem('Please sign in to access your timers.',401);return user;}
async function workspace(id:unknown,uid:string){if(typeof id!=='string')throw new Problem('Choose a workspace.');const row=await database().prepare('SELECT id FROM workspaces WHERE id=? AND owner=?').bind(id,uid).first();if(!row)throw new Problem('Workspace not found.',404);}
async function timer(id:unknown,uid:string){if(typeof id!=='string')throw new Problem('Choose a timer.');const row=await database().prepare('SELECT t.* FROM timers t JOIN workspaces w ON w.id=t.workspace_id WHERE t.id=? AND w.owner=?').bind(id,uid).first<{id:string;kind:string;started_at:string;reset_enabled:number}>();if(!row)throw new Problem('Timer not found.',404);return row;}
function failure(e:unknown){if(e instanceof Problem)return Response.json({error:e.message},{status:e.status,headers:cacheHeaders});if(e instanceof Error&&e.name==='ZodError')return Response.json({error:'Check the required fields, label lengths, and date.'},{status:400,headers:cacheHeaders});if(e instanceof Error&&e.message.includes('UNIQUE constraint'))return Response.json({error:'That name is already in use. Choose another.'},{status:409,headers:cacheHeaders});console.error('Tracker storage error',e);return Response.json({error:'We couldn’t reach your saved data. Please try again; your changes have not been confirmed.'},{status:503,headers:cacheHeaders})}
export async function GET(request:Request){try{const user=await owner();const db=database();const eventsFor=new URL(request.url).searchParams.get('timer');if(eventsFor){await timer(eventsFor,user.userId);const rows=await db.prepare('SELECT id,timer_id AS timerId,happened_at AS happenedAt,note,created_at AS createdAt FROM events WHERE timer_id=? ORDER BY happened_at DESC,created_at DESC').bind(eventsFor).all();return Response.json({events:rows.results},{headers:cacheHeaders})}
 // A deterministic per-user default prevents two devices creating duplicate initial workspaces.
 const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(user.userId));const initial='personal-'+Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,'0')).join('').slice(0,32);
 await db.prepare('INSERT OR IGNORE INTO workspaces (id,owner,name) SELECT ?,?,? WHERE NOT EXISTS (SELECT 1 FROM workspaces WHERE owner=?)').bind(initial,user.userId,'Personal',user.userId).run();
 const [ws,fs,ts,ls]=await Promise.all([db.prepare('SELECT id,name FROM workspaces WHERE owner=? ORDER BY rowid').bind(user.userId).all(),db.prepare('SELECT f.id,f.workspace_id AS workspaceId,f.name FROM folders f JOIN workspaces w ON w.id=f.workspace_id WHERE w.owner=? ORDER BY f.name').bind(user.userId).all(),db.prepare('SELECT t.id,t.workspace_id AS workspaceId,t.folder_id AS folderId,t.title,t.note,t.kind,t.started_at AS startedAt,t.reset_enabled AS resetEnabled,t.ended_at AS endedAt,t.counter,t.labels,t.color,t.emoji,(SELECT count(*) FROM events e WHERE e.timer_id=t.id) AS count,(SELECT max(happened_at) FROM events e WHERE e.timer_id=t.id) AS lastEvent FROM timers t JOIN workspaces w ON w.id=t.workspace_id WHERE w.owner=? ORDER BY t.rowid DESC').bind(user.userId).all(),db.prepare('SELECT l.id,l.workspace_id AS workspaceId,l.name FROM label_definitions l JOIN workspaces w ON w.id=l.workspace_id WHERE w.owner=? ORDER BY l.name').bind(user.userId).all()]);
 return Response.json({workspaces:ws.results,folders:fs.results,labels:ls.results,timers:ts.results.map(t=>({...t,resetEnabled:!!t.resetEnabled,counter:!!t.counter,labels:JSON.parse(t.labels as string)})),user:{name:user.fullName??'Your account',email:user.email}},{headers:cacheHeaders});
 }catch(e){return failure(e)}}
export async function POST(request:Request){try{const user=await owner();const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw new Problem('This request must come from your app.',403);const body=await request.json() as Record<string,unknown>;const db=database();
 if(body.action==='save-workspace'){const p=namedInput.parse(body);const old=await db.prepare('SELECT id FROM workspaces WHERE id=?').bind(p.id).first();if(old){await workspace(p.id,user.userId);await db.prepare('UPDATE workspaces SET name=? WHERE id=? AND owner=?').bind(p.name,p.id,user.userId).run()}else await db.prepare('INSERT INTO workspaces (id,owner,name) VALUES (?,?,?)').bind(p.id,user.userId,p.name).run();}
 else if(body.action==='save-folder'){const p=namedInput.parse(body);await workspace(p.workspaceId,user.userId);const old=await db.prepare('SELECT workspace_id AS workspaceId FROM folders WHERE id=?').bind(p.id).first<{workspaceId:string}>();if(old){if(old.workspaceId!==p.workspaceId)throw new Problem('Folder belongs to another workspace.',404);await db.prepare('UPDATE folders SET name=? WHERE id=?').bind(p.name,p.id).run()}else await db.prepare('INSERT INTO folders (id,workspace_id,name) VALUES (?,?,?)').bind(p.id,p.workspaceId,p.name).run();}
 else if(body.action==='save-label'){const p=namedInput.parse(body);await workspace(p.workspaceId,user.userId);const name=labelName.parse(p.name.replace(/^#/,''));await db.prepare('INSERT INTO label_definitions (id,workspace_id,name) VALUES (?,?,?) ON CONFLICT(workspace_id,name) DO NOTHING').bind(p.id,p.workspaceId,name).run();}
 else if(body.action==='save-timer'){const p=timerInput.parse(body);await workspace(p.workspaceId,user.userId);if(p.resetEnabled)assertTimerDate(p.kind,p.startedAt);if(p.folderId){const folder=await db.prepare('SELECT id FROM folders WHERE id=? AND workspace_id=?').bind(p.folderId,p.workspaceId).first();if(!folder)throw new Problem('Choose a folder in this workspace.');}if(p.kind==='until'&&p.counter)throw new Problem('Counters are available for days-since timers.');const old=await db.prepare('SELECT id FROM timers WHERE id=?').bind(p.id).first();if(old){await timer(p.id,user.userId);const first=await db.prepare('SELECT min(happened_at) AS date FROM events WHERE timer_id=?').bind(p.id).first<{date:string|null}>();if(first?.date&&(p.kind!=='since'||p.startedAt>first.date))throw new Problem('Keep the timer start on or before its first recorded event. Timers with history must remain days-since timers.');await db.prepare('UPDATE timers SET workspace_id=?,folder_id=?,title=?,note=?,kind=?,started_at=?,reset_enabled=?,ended_at=?,counter=?,labels=?,color=?,emoji=? WHERE id=?').bind(p.workspaceId,p.folderId,p.title,p.note,p.kind,p.startedAt,+p.resetEnabled,p.endedAt,+p.counter,JSON.stringify(p.labels),p.color,p.emoji,p.id).run()}else await db.prepare('INSERT INTO timers (id,workspace_id,folder_id,title,note,kind,started_at,reset_enabled,ended_at,counter,labels,color,emoji) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(p.id,p.workspaceId,p.folderId,p.title,p.note,p.kind,p.startedAt,+p.resetEnabled,p.endedAt,+p.counter,JSON.stringify(p.labels),p.color,p.emoji).run();}
 else if(body.action==='record-event'){const p=eventInput.parse(body);const t=await timer(p.timerId,user.userId);if(!t.reset_enabled)throw new Problem('Resets are disabled for this timer.');if(t.kind!=='since')throw new Problem('Countdown timers do not record resets.');assertEventDate(p.happenedAt,t.started_at);const old=await db.prepare('SELECT timer_id AS timerId FROM events WHERE id=?').bind(p.id).first<{timerId:string}>();if(old&&old.timerId!==p.timerId)throw new Problem('Event identifier already in use.',409);await db.prepare('INSERT OR IGNORE INTO events (id,timer_id,happened_at,note,created_at) VALUES (?,?,?,?,?)').bind(p.id,p.timerId,p.happenedAt,p.note,new Date().toISOString()).run();}
 else if(body.action==='delete-event'){const t=await timer(body.timerId,user.userId);if(typeof body.id!=='string')throw new Problem('Choose an event.');await db.prepare('DELETE FROM events WHERE id=? AND timer_id=?').bind(body.id,t.id).run();}
 else if(body.action==='delete-timer'){const t=await timer(body.id,user.userId);await db.batch([db.prepare('DELETE FROM events WHERE timer_id=?').bind(t.id),db.prepare('DELETE FROM timers WHERE id=?').bind(t.id)]);}
 else if(body.action==='delete-folder'){await workspace(body.workspaceId,user.userId);if(typeof body.id!=='string')throw new Problem('Choose a folder.');const f=await db.prepare('SELECT id FROM folders WHERE id=? AND workspace_id=?').bind(body.id,body.workspaceId).first();if(!f)throw new Problem('Folder not found.',404);await db.batch([db.prepare('UPDATE timers SET folder_id=NULL WHERE folder_id=?').bind(body.id),db.prepare('DELETE FROM folders WHERE id=?').bind(body.id)]);}
 else if(body.action==='delete-workspace'){await workspace(body.id,user.userId);const n=await db.prepare('SELECT count(*) AS n FROM workspaces WHERE owner=?').bind(user.userId).first<{n:number}>();if(!n||n.n<2)throw new Problem('Keep at least one workspace.');await db.batch([db.prepare('DELETE FROM events WHERE timer_id IN (SELECT id FROM timers WHERE workspace_id=?)').bind(body.id),db.prepare('DELETE FROM timers WHERE workspace_id=?').bind(body.id),db.prepare('DELETE FROM label_definitions WHERE workspace_id=?').bind(body.id),db.prepare('DELETE FROM folders WHERE workspace_id=?').bind(body.id),db.prepare('DELETE FROM workspaces WHERE id=? AND owner=?').bind(body.id,user.userId)]);}
 else throw new Problem('Unknown action.');
 return Response.json({ok:true},{headers:cacheHeaders});
 }catch(e){if(e instanceof Error&&(e.message.startsWith('A days-since')||e.message.startsWith('A recorded event')||e.message.startsWith('An event cannot')))return Response.json({error:e.message},{status:400,headers:cacheHeaders});return failure(e)}}
